const L=(id,slug,title,body)=>({id,theme:id.slice(0,2),slug,title,...body});
export const systems = [
L('05.01','combine_components','Combine fixed components into a useful system',{
 build:'A fixed research workflow that uses a task skill, an ML tool, domain checks, and a report checker.', why:'A language model’s answer is only one part of reliable experimental work. The surrounding system determines what it can observe, execute, and verify.', start:'The baseline skill, workflow graph, domain rules, and output checker.', budget:'One bike baseline fit and the existing checks.',
 how:'Keep the language model and procedures fixed. The skill chooses actions; the tool fits a model; the domain rules reject invalid inputs; the output checker verifies evidence. Their coordination can improve reliability without changing model weights or any component’s instructions.', predict:'Which component should stop a leaked feature before fitting?',
 steps:[['Assign responsibilities','Avoid giving every component an undefined job.','Create SYSTEM.md mapping framing, data checks, domain checks, fitting, metric checks, and reporting to the existing components. State what each reads and writes.','Responsibilities and evidence paths are explicit.'],['Run the fixed system','Observe coordinated behavior.','Run one valid baseline through the complete workflow. Then submit a target-derived feature fixture and confirm it stops before fitting. Retain the full trace.','The system produces one checked result and one meaningful refusal.']],
 check:'The valid run passes the intended checks. The invalid fixture does not reach fitting. No component is silently revised during the comparison.', change:'Remove the domain check in a labelled diagnostic copy. Replace fitting with a dry-run stub and reuse the leaked fixture without another fit. Record which protection is lost and whether another guard still blocks it.', takeaways:['System capability includes tools, state, and checks around the model.','Coordination can improve reliability with fixed components.','This course’s term “system intelligence” is not a standard RSI level.'],
 quiz:[['Did the language-model weights change?','No. The experiment changes system composition, not model training.'],['Which component computes MAE?','An executable metric tool or checker, operating on predictions and targets.'],['Does combining components prove self-improvement?','No. The components and their assembly can remain fixed.'],['What does the refusal demonstrate?','The executed workflow blocks the specific declared violation before spending a fit.']], next:'Different tasks may need different fixed skills. Make that choice explicit.'}),
L('05.02','route_tasks','Choose a skill for the task',{
 build:'A router that sends bike regression and wine classification to suitable fixed procedures.', why:'A metric or model that fits one task can be wrong for another. Reuse should preserve meaning.', start:'Both data cards, the domain vocabulary, and two fresh workspaces.', budget:'Two fits: one constant baseline for each task.',
 how:'The task brief identifies the target type and evaluation rule. Regression estimates a count and uses MAE. The derived wine classification task predicts whether quality is at least 7 and uses balanced accuracy. Routing chooses an already defined procedure; it does not learn a new one.', predict:'Would a majority-only wine classifier look better under accuracy than under balanced accuracy?',
 steps:[['Build the route table','Connect task meaning to method.','Write ROUTING.md with input task, target type, data card, model baseline, metric, and required checks. Reject an unrecognized task instead of guessing.','Each route has a scientifically appropriate metric.'],['Execute both routes','Test transfer of the system structure.','Run a constant bike baseline and a majority wine baseline. Inspect wine class balance and both class recalls. Save a comparison of what is shared and what differs.','The majority classifier has balanced accuracy 0.5 when both classes occur.']],
 check:'The two tasks use their own contracts. Identical wine feature rows stay in one partition. Unknown tasks are rejected.', change:'Give the router a task with no target type. Require a clarification of the scientific question before choosing a metric.', takeaways:['Routing selects a method for a known task.','Shared workflow structure does not mean shared metrics.','An unknown task should expose missing information.'],
 quiz:[['Why not use raw accuracy alone for wine?','Class imbalance can make majority prediction look strong while missing every positive example.'],['Is task routing self-organization?','Not by itself. A fixed route table is predefined organization.'],['What transfers from regression to classification?','Framing, provenance, split discipline, baseline comparison, evidence, and budgets.'],['What needs adaptation?','Target definition, models, metrics, error analysis, and relevant data checks.']], next:'Give the system the right reference information and current task state.'}),
L('05.03','context_and_state','Retrieve what matters and retain task state',{
 build:'A context packet that separates task rules, relevant knowledge, and current execution state.', why:'More text can add contradictions and stale instructions. Useful context is selected for a decision.', start:'The two data cards, a bike task brief, and a partially completed run ledger.', budget:'No fits. Two context-selection checks.',
 how:'Task rules define the current problem. Reference knowledge explains how to act. State records what has already happened. A retrieval step should select relevant references without overwriting current state. A past experiment’s final score is not a new task’s target to imitate.', predict:'Which is more important for resuming: a long generic ML article or the current candidate ledger?',
 steps:[['Build the packet','Separate information by role.','Create CONTEXT.md for resuming the bike run. Include current contract, candidate state, remaining budget, and the relevant data-card passages. Exclude wine-specific metric instructions and unrelated history.','The packet is short enough to inspect and sufficient for the next action.'],['Test stale context','Make a conflict visible.','Supply a labelled stale note that says the run has three attempts left when the ledger shows one. Have the state check reject the conflict and identify the authoritative record.','Retrieval cannot silently reset spent budget.']],
 check:'The packet preserves current task identity and ledger state. A stale budget note produces a visible conflict.', change:'Remove the data card’s input-availability rule and ask which next decision becomes unsafe to infer.', takeaways:['Knowledge and state serve different roles.','Retrieved text can be stale or irrelevant.','Authoritative state must survive context summarization.'],
 quiz:[['Is a context summary the original evidence?','No. It is a derived aid that should link back to authoritative artifacts.'],['Can more context reduce reliability?','Yes, through irrelevant instructions, contradictions, or stale state.'],['Which budget should the agent trust in the conflict?','The current verified experiment ledger, while recording the conflict.'],['Does saving context establish learning?','It establishes persistence. A behavior change and evidence of benefit require separate checks.']], next:'Coordinate the whole run, including conditions that need human judgment.'}),
L('05.04','coordinate','Coordinate planning, execution, and checking',{
 build:'A coordinator that advances work only when the required artifacts and checks are present.', why:'Good individual tools can still produce a weak system if nobody checks their handoffs.', start:'The fixed workflow, context packet, and matching candidate checks.', budget:'One baseline fit; two simulated handoff failures.',
 how:'The coordinator tracks task state, chooses the next allowed action, and handles incomplete evidence. It should stop when the scientific brief is ambiguous or a required check is missing. It does not acquire evaluator independence by naming a “reviewer” role in the same conversation.', predict:'Should a coordinator repair an ambiguous target definition automatically?',
 steps:[['Define the handoffs','Make completion requirements explicit.','Create a coordinator procedure with states ready, running, awaiting-check, complete, and needs-clarification. Define the artifact and condition for each transition. Save and read state before its permitted action, not only in a report afterward.','The next action follows a visible condition.'],['Run and interrupt handoffs','Test more than a successful path.','Run one baseline through the coordinator. Save awaiting-check and end the process. Resume from that state to check the result. Then test a missing checker result and an ambiguous target brief using fixtures. Save transitions and stop reasons. Do not invent human approval.','Incomplete evidence and scientific ambiguity take explicit stop paths.']],
 check:'The coordinator never marks incomplete work complete. Its report states that role separation is organizational unless an actual access boundary exists.', change:'Have a tool return a valid score for the wrong candidate. Require the coordinator to reject that handoff.', takeaways:['Reliable coordination checks both content and identity.','Some ambiguity changes the scientific task and needs clarification.','Role names do not create technical isolation.'],
 quiz:[['Why distinguish running from awaiting-check?','Computation may be finished while acceptance evidence is still missing.'],['Can a coordinator invent an approval to proceed?','No. It must record the actual decision or the unresolved need.'],['What should happen to a wrong-candidate score?','Reject the handoff and preserve the mismatch for diagnosis.'],['Does this fixed coordinator recursively improve?','No. Its control procedure remains unchanged.']], next:'Remove one component to test which benefits depend on it.'}),
L('05.05','ablate_system','Find which component makes the difference',{
 build:'An ablation that compares the system with and without one domain check.', why:'A successful full system does not reveal which component caused the benefit.', start:'The fixed coordinator and the leaked-feature fixture used earlier.', budget:'No fits. Four main fixture executions: two inputs under each of two system versions. The separate change below adds two more fixture executions.',
 how:'An ablation removes one component while holding the rest as steady as possible. Here the outcome is whether an invalid proposal reaches fitting. Use a dry-run fitting stub so the ablated system cannot accidentally train a leaked model. Reliability is the measured property, not prediction quality.', predict:'Will removing the domain check change the valid case, the invalid case, or both?',
 steps:[['Predeclare the outcome','Avoid choosing the metric after the result.','Write ABLATION-PLAN.md comparing full system and system without the domain check. Use the same valid and leaked-feature fixtures. Measure whether each reaches the fit stub.','The test targets the check’s specific job.'],['Run both versions','Measure the component’s contribution.','Execute both systems on both fixtures. Preserve the versions and outcomes. Explain any overlapping protection from another component rather than forcing the expected result.','Redundant checks may hide the effect of removing one component.']],
 check:'Only one component differs. The report accounts for redundant checks and does not claim a predictive-performance gain.', change:'Remove both overlapping checks in a separate declared ablation. Run the same valid and leaked fixtures through the fit stub, for two additional executions and no model fits. Explain why this answers a different causal question.', takeaways:['Ablation tests dependence on a component.','Redundancy can make one removal appear harmless.','The outcome must match the component’s purpose.'],
 quiz:[['Why use a fit stub?','It records whether execution would proceed without training on an intentionally invalid fixture.'],['Does no effect prove the component useless?','No. Another component may provide the same protection or the test may miss relevant cases.'],['Why not remove several components at once first?','That makes their individual contributions harder to separate.'],['Can this establish language-model improvement?','No. It measures a system-level reliability mechanism with fixed model weights.']], next:'You can describe a useful harness. Ask a builder to generate one from a task brief.'}),
L('06.01','write_a_brief','Describe the harness you need',{
 build:'A plain-language specification for a small bike-research harness.', why:'A generator needs the scientific and operating requirements, not just “make an intelligent agent.”', start:'The bike task, fixed system, and its observed failure cases.', budget:'No fits. One brief and one ambiguity review.',
 how:'A harness organizes an agent’s instructions, tools, state, evaluation, and limits. A harness brief states the task and required behavior while leaving implementation syntax to the coding agent. A good brief includes what must fail, not only what should succeed.', predict:'Which missing choice would make two generated harnesses incomparable?',
 steps:[['Write the intent','State scientific and operating rules.','Create HARNESS-BRIEF.md for bike regression. Include prediction setting, source, permitted inputs, split, MAE, baseline, two-attempt limit, outputs, stop rules, and refusal of leakage. Use prose and a small table only.','The brief is readable without knowing a configuration language.'],['Review ambiguity','Find missing decisions before generation.','Use build-ml-harness to inspect the brief without building yet. List ambiguous scientific choices and routine implementation choices separately. Resolve the scientific choices from the existing task contract.','The generator can proceed without guessing the definition of success.']],
 check:'The brief fixes target, inputs, metric, partitions, resources, and required rejection. It does not require the student to write code or schemas.', change:'Remove the metric and ask two plausible alternatives. Explain why choosing one after seeing results would be invalid.', takeaways:['A readable brief can control a generated system.','Scientific choices belong in the specification.','Required failures make acceptance testable.'],
 quiz:[['What is a harness in this course?','The organized instructions, tools, state, checks, and limits around task execution.'],['What does the builder decide?','Implementation details consistent with the brief, while surfacing unresolved scientific choices.'],['Why specify a refusal?','It lets you verify that the generated system respects a meaningful boundary.'],['Does the brief need JSON?','No. The agent can translate clear prose into any machine representation it needs.']], next:'Use the builder skill to turn that brief into actual files and behavior.'}),
L('06.02','generate','Generate a first harness',{
 build:'A generated harness with a runnable entry point, checks, and readable instructions.', why:'A specification is not executable until a builder turns it into tools and a workflow.', start:'HARNESS-BRIEF.md from 06.01 and a fresh generated-harness folder.', budget:'One baseline fit; no autonomous search. The dedicated refusal tests follow in 06.04.',
 how:'The builder is a meta-harness: it creates another harness. The generated harness performs the task. They have separate responsibilities and versions. The builder can stay fixed while producing different systems. Generation by itself does not imply self-improvement.', predict:'What output would distinguish a finished harness from a folder of plans?',
 steps:[['Generate the system','Let the agent supply implementation syntax.','Use build-ml-harness with HARNESS-BRIEF.md. Generate a README, task contract, workflow, tools, checks, dependency record, and recovery guide in my workspace. Prefer the supplied ML tools where appropriate.','The generated entry point names concrete operations.'],['Run the baseline','Prove that the generated system executes.','Run exactly one baseline fit from a clean subfolder under the brief’s frozen two-attempt limit. One fit uses one slot; do not redefine the contract as a one-attempt experiment. Save commands, exit status, predictions, and the checked result. Do not mark generation complete until the run finishes or a specific failure is recorded.','A real result supports the generated instructions.']],
 check:'The generated system executes its baseline. The result follows the original brief. Missing capabilities are reported, not replaced with simulated success.', change:'Ask what would happen if the builder were removed after generation. The generated harness should still have its required task instructions and dependencies.', takeaways:['A meta-harness generates a harness.','Generated files need an actual run.','The generator and generated system are distinct objects.'],
 quiz:[['Which object is the meta-harness?','The builder procedure that turns a brief into a runnable harness.'],['Can the builder remain unchanged?','Yes. A fixed generator can produce many task-specific systems.'],['Does a successful generated baseline establish RSI?','No. It establishes generation and execution, not inherited improvement of the builder.'],['What if code exists but dependencies are missing?','The execution requirement remains incomplete until setup works or the limitation is stated.']], next:'Inspect the generated decisions before trusting more of its behavior.'}),
L('06.03','inspect_generated','Inspect what the builder decided',{
 build:'A review that maps each important generated behavior back to the brief.', why:'A generator can quietly invent a split, skip a check, or increase the budget. Review should expose those choices.', start:'The generated harness and its first run.', budget:'No new fits. Inspect generated files and one trace.',
 how:'Trace requirements forward to implementation and evidence backward to requirements. For example, “two attempts maximum” should appear in control logic and an over-budget refusal. A sentence in the README alone does not show the limit runs.', predict:'Where would you look to verify the attempt limit?',
 steps:[['Map requirements','Connect intent to actual behavior.','Create REVIEW.md mapping target, features, split, metric, budget, refusal, and outputs to generated files and runtime evidence. Mark undocumented builder choices.','Every key requirement has an implementation location or a visible gap.'],['Inspect one hidden assumption','Find a plausible failure before it scales.','Inspect preprocessing and candidate selection. Verify transformations fit only on training data and selection uses the declared partition. Save the evidence and any repair needed.','The review reaches operations, not only documentation.']],
 check:'The review distinguishes stated, implemented, and executed requirements. Any generated assumption is explicit.', change:'In a diagnostic copy, alter the README’s budget while leaving code unchanged. Explain why a documentation-only review misses the mismatch.', takeaways:['Generated implementation can drift from intent.','A requirement needs both code and behavioral evidence when applicable.','Readable documentation is not enforcement.'],
 quiz:[['What is traceability here?','The connection from requirement to implementation to observed check result.'],['Why inspect train-only preprocessing?','Evaluation information can leak through transformations even without using labels directly.'],['Does a README limit constrain execution by itself?','No. The running procedure or tool must apply it.'],['What should happen to an undocumented scientific assumption?','Make it explicit and resolve it against the brief before accepting the result.']], next:'Test the generated system with an input it is supposed to refuse.'}),
L('06.04','test_refusal','Test the generated harness’s boundaries',{
 build:'A retained valid run and two meaningful refusals from the generated harness.', why:'A system that only succeeds on valid inputs may still accept the mistakes it claims to prevent.', start:'The reviewed harness and a fresh test workspace.', budget:'Two admitted attempts: one valid fit and one leaked-input failure before fitting. A third distinct request must be refused on budget. No extra fit for either refusal.',
 how:'A negative test supplies a specific forbidden request and checks the resulting behavior. The requested action, candidate, run, and contract must match the evidence used to decide it. An unrelated old approval or successful report must not authorize this request.', predict:'Could an old successful result from another run accidentally satisfy a weak check?',
 steps:[['Run a valid case','Establish the intended path.','Execute one valid baseline and retain its exact run and candidate identity. Save the completed checks.','The success evidence belongs to this run.'],['Attempt two violations','Check request-specific enforcement.','Submit a leaked-feature request and an over-budget request. Also place an unrelated successful report in a separate fixture folder. Confirm it cannot authorize either request. Keep refusals and fit counts.','Rejection depends on the current request and contract.']],
 check:'Invalid requests do not fit models. An unrelated result cannot satisfy the current candidate’s check. All attempts and refusal costs remain visible.', change:'Remove candidate identity from a check fixture and verify that the system treats it as incomplete evidence.', takeaways:['Checks must bind to the action they authorize.','Old success evidence is not a general permission token.','Refusal behavior needs execution tests.'],
 quiz:[['Why test an unrelated old report?','It catches a broad search that treats any success file as sufficient evidence.'],['Should a missing candidate ID be accepted?','No. The checker cannot establish which object the result describes.'],['Does a local refusal prove an adversarial sandbox?','No. A host agent with write access can bypass local logic. State that boundary.'],['What is a useful failure result?','A clear refusal tied to the actual request, with no unauthorized fit and a retained record.']], next:'Generate a harness for a different task to test whether the builder adapts.'}),
L('06.05','second_task','Generate a classification harness',{
 build:'A wine-classification harness generated from a revised readable brief.', why:'A useful builder adapts scientific choices instead of copying regression labels into a new folder.', start:'The fixed builder skill and wine data card. New task brief and workspace.', budget:'Two wine fits: majority baseline and balanced logistic model.',
 how:'Preserve the high-level data science workflow. Change the target to quality at least 7, use grouped input duplicates, and measure balanced accuracy with class recalls. These changes arise from the task’s meaning. The builder’s own procedure can remain fixed.', predict:'Which parts of the bike harness can transfer unchanged?',
 steps:[['Describe the new task','Keep the student interface readable.','Write a wine HARNESS-BRIEF.md from the data card. Predeclare the binary threshold, the fixed wine-v1 split that keeps identical input vectors together, balanced accuracy, both class recalls, two-fit budget, and source attribution.','The brief makes the derived label explicit.'],['Generate and compare','Test actual adaptation.','Use the unchanged builder to generate and run the classification harness. Fit the majority and balanced logistic candidates. Compare generated task, preprocessing, metric, and error analysis with the bike harness.','The classification report includes minority-class behavior.']],
 check:'The builder uses the classification contract. Identical feature rows do not cross partitions. The comparison explains shared workflow and changed scientific components.', change:'Ask for an ordinal wine task in a new brief without running it. Identify why the binary evaluator cannot be reused unchanged.', takeaways:['A fixed generator can adapt outputs to different briefs.','Task transfer requires semantic changes, not filename changes.','A derived label should be declared before evaluation.'],
 quiz:[['Did the builder improve merely by generating the second harness?','No. Its procedure may be identical. The output adapted to a different input.'],['Why group repeated feature rows?','Otherwise identical inputs can appear in both training and evaluation and inflate the comparison. This check does not remove every near-duplicate.'],['Why report class recalls?','Balanced accuracy summarizes them; inspecting each reveals asymmetric failures.'],['What does this demonstrate?','A small task-transfer example for the generated workflow, not universal generator capability.']], next:'Check whether both generated systems run again from their saved packages and handoffs.'}),
L('06.06','recreate','Recreate and compare generated harnesses',{
 build:'A clean-start reproducibility report for two generated harnesses.', why:'A generated system that depends on hidden local state is difficult to share or evaluate.', start:'Both briefs, generated harnesses, dependency records, and prior results.', budget:'Two baseline fits and two wrong-task refusal checks, one of each per task. Refusals add no model fits. No new search.',
 how:'Recreation uses the saved brief, builder version, generated files, dependencies, and data versions. Different source code can implement the same contract, so compare behavior and evidence as well as file hashes. If generation is stochastic, do not assume byte-identical output.', predict:'Must two valid generated harnesses have identical code?',
 steps:[['Prepare the clean starts','Remove dependence on the old chat.','Write a handoff for each harness with brief, builder version, generated entry point, pinned data, setup, and acceptance checks. Create clean output folders.','A reader can locate every dependency.'],['Reproduce and explain','Compare behavior under the same task contract.','Run each baseline from the saved generated system in a new output folder. Submit one wrong-task request to each package and retain its refusal without another fit. Compare predictions, metric, refusal behavior, and versions with the earlier run. Record any difference without selecting the most favorable rerun.','The report distinguishes reproduction of behavior from identical generated text.']],
 check:'Both task contracts remain intact. Actual runs and negative checks are recorded. The report does not confuse generator output diversity with improvement.', change:'Change the builder’s proposal instructions and label it a new builder version. State the comparison needed before calling it a better builder.', takeaways:['Saved generation inputs support reproducibility.','Behavioral equivalence can matter more than identical code.','Improving a builder requires comparing builders, not just their artifacts.'],
 quiz:[['What must be versioned?','Brief, builder, generated harness, data, dependencies, and evaluator contract.'],['Is differing code automatically a failure?','No. Check whether it satisfies the same declared behavior and evidence requirements.'],['Can a favorable rerun replace an unfavorable original silently?','No. Preserve both and account for the additional selection opportunity and cost.'],['What would test a better builder?','Matched-budget comparisons of harnesses it produces across prespecified fresh tasks and failure cases.']], next:'Before changing the system itself, distinguish the different self-* mechanisms.'}),
];
