import {foundation} from './lessons-foundation.mjs';
import {structure} from './lessons-structure.mjs';
import {systems} from './lessons-systems.mjs';
import {improvement} from './lessons-improvement.mjs';
import {research} from './lessons-research.mjs';
import {science} from './lessons-science.mjs';
import {frontier} from './lessons-frontier.mjs';
import {capstones} from './lessons-capstone.mjs';
export const themes = {
  '00': {directory:'00_start_here', title:'Start with a prediction', intro:'A bike service wants an estimate of hourly demand. Before building an improving agent, learn to tell an executed prediction from a convincing description.', bridge:'You need basic familiarity with tables and prediction error. You do not need RSI, agent, or infrastructure experience.', exit:'You are ready to continue when you can name the target, identify a measured result, and explain one way a good-looking score can mislead.'},
  '01': {directory:'01_process_without_loops', title:'Make one process dependable', intro:'You can inspect an agent’s output. Now make the actions behind it explicit and repeatable. Run a simple data science process once, then package it as a skill.', bridge:'The process stays fixed. “No loops” means no learner-designed search or revision loop. The coding agent and numerical libraries can still have internal iterations.', exit:'A repeatable process gives you a useful starting point. The next theme asks what to do when that process produces a weak result.'},
  '02': {directory:'02_loop_engineering', title:'Repeat for a reason', intro:'A weak result invites another attempt. Repeating only helps when you know what to change, how to remember the current state, and when to stop.', bridge:'Use the baseline and readable skill from the previous theme. Add feedback, state, and budgets one at a time.', exit:'A loop handles repeated work. It does not explain why a data failure and an expensive model should take different routes. That calls for a graph.'},
  '03': {directory:'03_graph_engineering', title:'Give different cases different routes', intro:'A workflow is more than a numbered list. Some actions depend on others. Some can proceed independently. Some should run only after a particular failure.', bridge:'You already have a bounded improvement loop. Now place it inside a graph of dependencies, branches, and recovery paths.', exit:'A graph tells the agent where work goes. The next theme asks whether the objects moving through it have the right meaning.'},
  '04': {directory:'04_ontology_engineering', title:'Agree on what the experiment means', intro:'Two files can both say “score” while describing different measurements. A shared vocabulary connects the data, models, decisions, and evidence.', bridge:'Begin with concrete entities and relations in Markdown. Add only the rules needed to catch a real inconsistency.', exit:'You can now inspect both the route of an experiment and the meaning of its records. These become parts of a coordinated research system.'},
  '05': {directory:'05_system_intelligence', title:'Build capability around the model', intro:'A useful research system combines a model with tools, state, checks, and domain knowledge. In this course, “system intelligence” means the capability of that combination.', bridge:'This is a course term, not an accepted RSI level. Keep the components fixed while studying how their coordination changes results.', exit:'Once you can describe a useful system, you can ask another procedure to build it from a brief.'},
  '06': {directory:'06_meta_harness_engineering', title:'Generate a harness from a brief', intro:'A harness organizes execution: instructions, tools, state, checks, and limits. A meta-harness generates such a system from a task description.', bridge:'You have built the parts by hand through natural language. Now the agent assembles them and proves that the result runs.', exit:'Generating a system is distinct from improving the generator. Before recursion, separate the many meanings of “self”.'},
  '07': {directory:'07_understanding_self_star', title:'Separate the self-* ideas', intro:'Correction, reflection, learning, improvement, organization, emergence, self-play, and modification describe different properties. They can overlap; they are not interchangeable.', bridge:'Most labs use the small ML workflow. Queue simulations expose organization and emergence; a tiny game exposes actual self-play learning. Ask what persists and what observation would establish a benefit.', exit:'A mechanism can exist without helping. The next theme makes the evidence for improvement explicit.'},
  '08': {directory:'08_measuring_improvement', title:'Measure what improved', intro:'A better score can come from a better method, more attempts, easier data, or an evaluation mistake. Design comparisons that separate those explanations.', bridge:'Use the fixed and modified skills from earlier themes. Freeze the comparison before reading its result.', exit:'You can now ask a sharper recursive question: does the changed procedure produce better future improvements?'},
  '09': {directory:'09_recursive_self_improvement', title:'Improve the improvement procedure', intro:'The solver proposes ML experiments. The improver revises the solver’s research skill. Recursion enters when an improvement procedure is itself revised and that revision governs later improvement work.', bridge:'Track three separate objects: task solver, improver, and evaluator. Keep claims of structure, effectiveness, and acceleration separate.', exit:'A bounded recursive experiment is now inspectable. The research studio shows how current systems combine these mechanisms and where their evidence ends.'},
  '10': {directory:'10_research_studio', title:'Read and rebuild recent research', intro:'Study the mechanism before the headline. Each studio lab maps a recent primary source to a small executable activity or an explicit result audit.', bridge:'Complete the foundation themes first. Laptop adaptations preserve an idea, not the scale or headline result of the original system.', exit:'Use the capstones to transfer the ideas to a new task and defend your conclusions with evidence.'},
  '11': {directory:'11_capstones', title:'Build, transfer, and explain', intro:'Your final work should be understandable to another student. Give them a task, a runnable system, an honest result, and a clear explanation of its limits.', bridge:'Use the tools and skills that your experiment needs. A larger architecture is not automatically a better answer.', exit:'Keep the portfolio small enough to inspect and complete enough to reproduce. A well-explained failure can be a strong final project.'},
};
export const lessons = [...foundation, ...structure, ...systems, ...improvement, ...research, ...science, ...frontier, ...capstones];
