import {R} from './lessons-research.mjs';
export const science = [
R(18,'06_scientist_two','hypothesis','Turn a limitation into a scientific hypothesis','scientist',{
 build:'A baseline, a testable hypothesis, and a prespecified experiment.', why:'An interesting idea becomes a research question when you can state what evidence would support or contradict it.', start:'The bike baseline and selection error slices. No final outcomes.', budget:'Two fits: baseline and one intervention.',
 how:'ScientistTwo motivates a research workflow built around hypotheses and experiments. Our classroom question is narrow: does adding permitted weather information help a fixed linear recipe beyond calendar inputs? This is a prediction study, not a causal claim about weather.', predict:'What observation would make you reject the proposed explanation?',
 steps:[['Write the hypothesis','Connect a limitation to a measurable consequence.','Create HYPOTHESIS.md with observed limitation, proposed mechanism, intervention, metric, baseline, expected result, alternative explanation, and rejection condition. Use the fixed bike contract.','The hypothesis could be wrong.'],['Run the experiment','Produce evidence for the stated question.','Fit linear/calendar and linear/all under matching settings. Save predictions, slice errors, costs, and a conclusion tied to the predeclared question.','The conclusion addresses the intervention rather than a broad intelligence claim.']],
 check:'The hypothesis precedes results. One declared factor changes. A failed hypothesis remains a valid research outcome.', change:'Rewrite “weather improves demand prediction” as a conditional statement tied to this task, model, period, and metric.', takeaways:['A hypothesis predicts an observable difference.','A baseline defines the comparison.','Predictive evidence is not automatically causal evidence.'],
 quiz:[['Why include an alternative explanation?','It prevents treating one favorable outcome as uniquely proving the proposed mechanism.'],['What is the intervention?','Adding the permitted weather feature group while holding the linear recipe and evaluation fixed.'],['Does this reproduce autonomous scientific discovery?','No. It is a small mechanism exercise with a supplied task and limited search.'],['What makes a negative result useful?','It rules out or narrows a hypothesis under the tested conditions.']], next:'Screen ideas cheaply, then use ablations to test contributions.'}),
R(19,'06_scientist_two','screen_ablate','Screen ideas and test their contributions','scientist',{
 build:'A small screening table followed by a controlled ablation.', why:'Testing every idea at full scale is costly. Cheap screening can help, but it can also select for the wrong proxy.', start:'Two candidate hypotheses and a fixed development protocol.', budget:'Four fits maximum: two screening runs and two confirmation runs.',
 how:'Screening uses a cheaper test to choose which idea deserves more work. Confirmation then tests the chosen idea under the declared fuller conditions. An ablation removes the proposed component. Keep screening and confirmation results distinct; a cheap proxy is not automatically the final objective.', predict:'Could the idea that wins a small-data screen lose on the full training period?',
 steps:[['Declare the screen','Specify what the cheap test can establish.','Plan two small development-only screening experiments. State subset selection, metric, cost limit, and the rule for advancing one idea. Have the agent generate a separate screening runner; the supplied general tool keeps its training partition fixed. Preserve the original data and contracts, fit preprocessing only on the declared training subset, and keep final data untouched.','The proxy and its limitations are explicit.'],['Confirm and ablate','Test the selected contribution.','Run the selected idea and its ablation under matching fuller conditions within the total fit budget. Record whether the selected contribution holds under the fuller conditions. Do not claim a full-scale ranking of both screened ideas; only the selected idea received confirmation.','The selected contribution can fail confirmation.']],
 check:'The screen does not consume final evaluation. Confirmation and ablation use matched conditions. All ideas and costs are retained.', change:'Select on the fastest screen only and explain why that could miss an idea whose benefit appears at a larger data scale.', takeaways:['Cheap screens are allocation tools.','A proxy can rank ideas incorrectly.','Ablations test a component’s contribution.'],
 quiz:[['Why use screening?','To allocate limited research resources among ideas.'],['What is its main risk?','The cheap proxy may not preserve the ranking under the target conditions.'],['What does an ablation remove?','The specific proposed component while keeping the comparison otherwise similar.'],['Can the screening winner be reported as confirmed?','Only after the declared confirmation actually runs and supports that claim.']], next:'Turn a review criticism into another test instead of a more confident paragraph.'}),
R(20,'06_scientist_two','review_rebuttal','Answer a criticism with evidence','scientist',{
 build:'A review, a follow-up experiment, and an evidence-based response.', why:'A rebuttal should resolve an uncertainty, not merely defend the original wording.', start:'The hypothesis report and ablation results.', budget:'One follow-up comparison, at most two fits.',
 how:'A reviewer can identify a missing baseline, confound, or unsupported generalization. Convert one valid criticism into an experiment. Automated review is useful feedback but is not a real conference acceptance decision. ScientistTwo’s automated assessment must be read with that distinction.', predict:'What criticism can be resolved with an experiment rather than a wording change?',
 steps:[['Review the claim','Identify one consequential weakness.','Use audit-rsi-claim to review the research note. Separate a factual error, an unsupported inference, and a useful next experiment. Label the review as agent-generated in the current context.','The review’s source and limits are clear.'],['Respond through a test','Let new evidence change the conclusion.','Choose one criticism, predeclare a two-fit follow-up, and execute it. Write RESPONSE.md linking the new result and the revised claim. If the criticism stands, say so.','The response can narrow the original conclusion.']],
 check:'The response cites actual new evidence or identifies an unresolved issue. No automated score is presented as human peer acceptance.', change:'Write a response that only restates the original claim. Explain which uncertainty remains unchanged.', takeaways:['Review can reveal a missing experiment.','A rebuttal can concede or narrow a claim.','Automated evaluation and real peer review are different evidence.'],
 quiz:[['What makes a criticism actionable?','It identifies a concrete uncertainty or error that evidence or a precise correction can address.'],['Must a rebuttal prove the reviewer wrong?','No. It should establish the most accurate conclusion.'],['Does an agent reviewer create independent evidence?','Not automatically, especially when it shares context and assumptions.'],['Can an automated acceptance score be called conference acceptance?','No. Those are different events and decision processes.']], next:'Use a result as the next baseline, then inspect what actually improved.'}),
R(21,'06_scientist_two','successive_results','Distinguish better discoveries from a better scientist','scientist',{
 build:'A two-step research lineage and an audit of the researcher’s own changes.', why:'Successively better scientific artifacts do not alone show that the research procedure improved.', start:'Two completed hypothesis studies and their researcher instructions.', budget:'No fits required; optional one fresh test only if predeclared.',
 how:'A previous result can become the baseline for a new investigation. Track the result lineage separately from the researcher version. If the procedure stays fixed while solutions improve, the evidence concerns accumulated research outputs. Testing a better researcher needs a comparison of research processes.', predict:'Can a fixed scientist procedure produce several better solutions in sequence?',
 steps:[['Trace successive results','Separate artifacts from their producer.','Create DISCOVERY-LINEAGE.md with hypotheses, baselines, retained results, and costs. Add the researcher-procedure hash to every edge.','Result progression and researcher changes are visible separately.'],['Audit the claim','Apply the same standard to local and paper-reported work.','Use audit-rsi-claim to classify your lineage. Read ScientistTwo’s evaluation sections and state which outputs they assess. Distinguish improved scientific artifacts from demonstrated improvement of an improver.','The conclusion follows the measured object.']],
 check:'The audit names the evaluated object. It does not infer researcher self-improvement from successive task gains alone.', change:'Propose a matched experiment where old and new researcher procedures start from the same fresh baseline.', takeaways:['Research artifacts and research procedures have different lineages.','Successive discovery can use a fixed method.','A stronger researcher claim needs a stronger comparison.'],
 quiz:[['What can a rising solution score show?','Improved retained task artifacts under their evaluation conditions.'],['What does an unchanged researcher hash suggest?','The stored procedure did not change, though other context or state still needs inspection.'],['What compares researcher quality?','Research outcomes produced from matched fresh starts under comparable resources.'],['Does the laptop exercise validate frontier scientific performance?','No. It teaches the structure of the research and evidence questions.']], next:'Study how researcher requests and corrections become executable tasks.'}),
R(22,'07_sciencebuddy','human_task','Turn a researcher correction into a task','buddy',{
 build:'A task and rubric derived from a labelled researcher-request fixture.', why:'Human feedback is most useful when the system can connect it to an artifact and an observable requirement.', start:'A supplied classroom fixture: “Compare these wine models; do not hide failure on rare high-quality wines.” Use your existing predictions.', budget:'No fits. One rubric and two report checks.',
 how:'ScienceBuddy connects scientific interactions and artifacts to improvement work. Our fixture uses familiar classification evidence. A rubric turns the correction into checks: state the label threshold, report both class recalls, preserve predictions, and avoid claiming accuracy alone establishes quality. It is a teaching fixture, not a real scientist interaction.', predict:'Which part of the request can become an executable check?',
 steps:[['Extract the requirement','Retain the human-origin distinction.','Save the quoted classroom request as a labelled synthetic fixture. Create TASK.md and RUBRIC.md with observable criteria and evidence needed for each. Do not present it as an actual expert interview.','The correction becomes a testable requirement.'],['Test the rubric','Compare a complete and incomplete report.','Check one report containing both class recalls and a copy omitting minority recall. Generate any needed checker and retain both verdicts.','The rubric detects the omission it was designed to catch.']],
 check:'Fixture origin is explicit. Criteria connect to observable evidence. The test does not claim domain-expert validation.', change:'Read a small GWAS example at the conceptual level: genetic variants are tested for association with a trait. Explain why statistical association is not a causal or clinical recommendation and why domain review is still needed.', takeaways:['A correction should connect to an artifact and a check.','Human, synthetic, and model-generated feedback have different provenance.','A runnable rubric covers only its declared criteria.'],
 quiz:[['What is the human-grounded idea?','Convert a researcher’s actual task context and corrections into observable improvement targets.'],['Is this fixture real expert feedback?','No. It is a clearly labelled classroom construction.'],['Why include evidence requirements in a rubric?','Otherwise a report can claim compliance without supplying the underlying result.'],['Does a simple rubric replace scientific expertise?','No. Domain validity may require expert judgment, replication, or measurement.']], next:'Change the harness while keeping language-model weights fixed.'}),
R(23,'07_sciencebuddy','harness_adaptation','Adapt the harness to the rubric','buddy',{
 build:'A reporting-skill revision that responds to the rubric without changing model weights.', why:'Harness adaptation is often confused with training. Track the surface that actually changes.', start:'The task, rubric, and failed report fixture from 10.22.', budget:'One skill edit and four checker runs: parent and child on complete and incomplete evidence fixtures. No model-weight training.',
 how:'Keep the agent’s language-model weights fixed. Edit a learner-owned reporting skill to require class-wise evidence and a claim check. Then test the revised procedure. This isolates harness adaptation; it does not implement the paper’s weight-learning component.', predict:'Would saving a new reporting instruction change the language model’s parameters?',
 steps:[['Revise the procedure','Target the observed omission.','Create a child reporting skill from the failed rubric case. Require evidence-linked class recalls and an explicit limit statement. Preserve parent and child versions.','The changed artifact is an external skill.'],['Run the rubric checks','Measure the revised behavior.','Use parent and child on the same complete and incomplete evidence fixtures, making four report/check pairs. Retain every output and verdict. Do not invent missing class evidence to satisfy the rubric. State whether the shared agent context limits causal interpretation.','The child’s actual output can be compared with its parent.']],
 check:'The report names a harness change and does not claim a weight update. Both positive and negative rubric cases are exercised.', change:'Make the child skill longer without adding a useful requirement. Explain why more instructions need not improve the result.', takeaways:['Harness edits and parameter updates are distinct mechanisms.','Rubric feedback can target a narrow procedural omission.','Instruction length is not a quality measure.'],
 quiz:[['What changed in this lab?','The external reporting procedure.'],['What stayed fixed?','The language-model weights and the evaluation rubric.'],['Does a passing rubric prove general scientific competence?','No. It checks the declared task criteria.'],['What evidence would show actual weight training?','A training process with parameter updates, checkpoints, objective, data, and evaluation records.']], next:'Understand the grouped-reward calculation before discussing real GRPO training.'}),
R(24,'07_sciencebuddy','grpo','See what grouped rewards contribute','buddy',{
 build:'A tiny numerical grouped-reward update illustration with an explicit limit statement.', why:'The phrase “GRPO learning” can hide the distinction between scoring outputs and updating a policy.', start:'Four synthetic rollout rewards: 0, 0, 1, 1. A small generated calculation; no pretrained model.', budget:'One CPU numerical calculation and two edge cases; no LLM training.',
 how:'A rollout is one sampled attempt. A reward scores it. In a grouped-relative illustration, subtract the group mean and divide by its standard deviation plus a small stabilizer. Above-average attempts receive positive advantages; below-average attempts receive negative ones. Real GRPO adds token probabilities, policy ratios, clipping, a reference/KL treatment as specified by the implementation, sampling, and optimization. This calculation is not that training system.', predict:'What happens when all four rewards are identical?',
 steps:[['Calculate advantages','Expose the signal behind the update.','Generate a small CPU tool for rewards 0,0,1,1. Print mean, population standard deviation, normalized advantages, and a labelled toy categorical-policy update. Define the toy objective and learning rate. Save code and output.','Relative reward supplies a direction, not a guarantee of better future behavior.'],['Test edge cases','Make the limits concrete.','Repeat with all-equal rewards and one incorrectly scored rollout. Show zero centered signal in the equal case and how a wrong reward can push the toy policy in the wrong direction. Label every result numerical illustration.','Reward quality controls the direction of learning.']],
 check:'The calculation is reproducible and handles zero variance. No LLM checkpoint is claimed. The report lists missing pieces of real training.', change:'Use the scale skill to draft, without launching, a real training checklist: source implementation, model license, rollout data, reward validation, GPU memory, optimizer, checkpoints, and held-out evaluation.', takeaways:['Rewards and advantages are different quantities.','An update follows the supplied reward signal, even when it is wrong.','A toy calculation does not reproduce GRPO training.'],
 quiz:[['Why subtract the group mean?','It expresses each attempt’s reward relative to the group rather than using only its raw magnitude.'],['What if all rewards are equal?','Centered advantages are zero in this illustration, so there is no within-group preference signal.'],['Does positive advantage guarantee a correct scientific answer?','No. It depends on the reward’s validity and the comparison group.'],['What distinguishes actual LLM training here?','Parameter optimization over sampled token trajectories under the full declared objective and training setup.']], next:'Track harness and model versions together across coupled cycles.'}),
R(25,'07_sciencebuddy','coevolution','Track model–harness pairs across cycles','buddy',{
 build:'A version table and a small labelled simulation of alternating model and harness changes.', why:'A model checkpoint can perform differently with a new harness. Evaluate the pair that actually runs.', start:'Two synthetic model versions and two synthetic harness versions, plus a declared outcome table.', budget:'Four table evaluations in a simulation; no LLM training.',
 how:'ScienceBuddy couples harness adaptation with weight learning across repeated cycles. Our simulation represents the pair explicitly. It is constructed to show interaction: a harness may suit one model better than another. Synthetic scores illustrate the accounting and comparison, not the paper’s measured gains.', predict:'Must the best harness for model A remain best for model B?',
 steps:[['Define paired state','Avoid mixing incompatible versions.','Generate a labelled synthetic 2-by-2 table of model and harness versions with an interaction. Record the constructed values and why they illustrate the concept. Create PAIRS.md with both version IDs for each result.','Each result belongs to a pair.'],['Simulate the cycle','Track what changes at each stage.','Run one harness-selection step, one model-update placeholder, and another harness-selection step over the table. Mark the model update as a simulation, not training. Keep a fixed evaluation table.','Changing one component can change the best partner.']],
 check:'Every simulated result names both versions. Synthetic values are never mixed with paper or classroom measurements. The fixed reflector and feedback-source distinctions are checked against the paper.', change:'Draft a larger-compute extension that replaces the placeholder with real training and specifies how checkpoints, rewards, and paired evaluation would be recorded.', takeaways:['Evaluate the model–harness pair.','Alternating changes can interact.','A simulated update must remain visibly distinct from training.'],
 quiz:[['Why track both versions?','The deployed behavior depends on their combination.'],['Can a harness gain be attributed to weights alone?','Not without a comparison that holds the harness fixed.'],['What does this simulation establish?','How to track and reason about coupled state, not empirical co-evolution performance.'],['What is needed for a real extension?','Actual training and harness execution with source-aligned data, rewards, resources, checkpoints, and evaluation.']], next:'Audit the reported gains without mixing metrics or feedback sources.'}),
R(26,'07_sciencebuddy','audit_results','Read the ScienceBuddy results precisely','buddy',{
 build:'A result audit that separates single-attempt accuracy, multi-attempt coverage, and feedback provenance.', why:'Similar-looking percentages can describe different experiments and support different claims.', start:'The primary paper’s method, evaluation, and results sections; your numerical and harness exercises.', budget:'No training or fits. One source-linked audit and arithmetic check.',
 how:'The paper reports held-out single-attempt accuracy rising from 42.2% to 73.3% across three coupled cycles: a 31.1 percentage-point gain. That is not a 31.1% relative increase. Keep this result separate from validation-only harness changes and multi-attempt coverage. Distinguish real researcher interactions, simulated procedural feedback, and rubric-derived training rewards.', predict:'Would pass-at-four coverage be directly comparable with single-attempt accuracy?',
 steps:[['Reconstruct the comparison','Read definitions beside numbers.','Create RESULTS-AUDIT.md with each selected metric, split, number of attempts, baseline, final value, feedback source, and paper section. Recompute percentage-point and relative changes with a small tool.','The same number can mean different things under different denominators.'],['Audit the mechanism claim','Separate changed and fixed components.','Map the reported harness and weight changes, coupled cycles, and fixed reflector. Contrast the full study with your laptop exercises. State what you did not reproduce and what would require GPU training.','The classroom record and paper record remain distinct.']],
 check:'The audit reports 31.1 percentage points correctly. It does not mix coverage, validation, and held-out single-attempt metrics. Feedback sources are not all called human.', change:'Rewrite an overbroad headline as a source-scoped statement including task family, metric, and reported-evidence status.', takeaways:['Metric definitions belong beside results.','Human-grounded systems can also use synthetic and model-derived feedback.','Co-evolution does not imply that every component changes.'],
 quiz:[['What is the percentage-point change?','73.3 minus 42.2 equals 31.1 percentage points.'],['Why is pass-at-four different?','It allows multiple attempts and measures coverage under that opportunity, not one-attempt accuracy.'],['Did the laptop lab reproduce the training result?','No. It ran harness checks and numerical or synthetic illustrations.'],['Why identify the fixed reflector?','It prevents claiming that every improvement component recursively changed.']], next:'Compare ways of storing experience and refining reusable procedures.'}),
];
