"""Phased author walkthrough; stop for real hypothesis, selection, and review notes."""
import argparse
import csv
import hashlib
import shutil
import subprocess
import sys
import time
from pathlib import Path

p=argparse.ArgumentParser()
p.add_argument('phase',choices=['prepare','hypothesis','screen','confirm','followup','seal'])
p.add_argument('--output',type=Path,required=True)
a=p.parse_args()
repo=Path(__file__).resolve().parents[3]
out=a.output.resolve()
if out==repo or repo in out.parents:raise SystemExit('Use a sibling workspace')
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def save(name,body):
    path=out/name;path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(body.rstrip()+'\n',encoding='utf-8',newline='\n')
def rows(path):
    with path.open(encoding='utf-8',newline='') as stream:return list(csv.DictReader(stream))
def table(name,cols,values):
    path=out/name;path.parent.mkdir(parents=True,exist_ok=True)
    with path.open('w',encoding='utf-8',newline='') as stream:
        writer=csv.writer(stream,lineterminator='\n');writer.writerow(cols);writer.writerows(values)
def fields(path):return dict(line.split(': ',1) for line in path.read_text().splitlines() if ': ' in line)
def absent(name):
    if (out/name).exists():raise SystemExit('Preserve existing phase: '+name)
def command(label,parts):
    start=time.perf_counter()
    try:
        result=subprocess.run([sys.executable,*map(str,parts)],cwd=repo,capture_output=True,text=True,timeout=60)
        code,stdout,stderr=result.returncode,result.stdout,result.stderr
    except subprocess.TimeoutExpired as exc:
        code,stdout,stderr=124,str(exc.stdout or ''),'60-second timeout; preserve attempt'
    elapsed=time.perf_counter()-start
    save('commands/'+label+'.md',f'# {label}\n\nExit: {code}\nWall seconds: {elapsed:.9f}\n\nStdout:\n{stdout}\nStderr:\n{stderr or "(empty)"}')
    with (out/'COMMANDS.csv').open('a',encoding='utf-8',newline='') as stream:csv.writer(stream,lineterminator='\n').writerow([label,code,elapsed])
    if code:raise SystemExit('Inspect failed command: '+label)
def freeze():
    for row in rows(out/'SOURCE-HASHES.csv'):
        if sha(repo/row['path'])!=row['sha256']:raise SystemExit('Source changed: '+row['path'])
    if sha(out/'RESEARCHER.md')!=fields(out/'RESEARCHER-FREEZE.md')['SHA-256']:raise SystemExit('Researcher changed')
def fit(label,model,features,seed,index,note):
    freeze();workspace=out/label/'experiment'
    save(label+f'/before-{index}.md',f'# Before fit\n\nModel: {model}\nFeatures: {features}\nSeed: {seed}\nAttempt: {index} of 2\nResearcher SHA-256: {sha(out/"RESEARCHER.md")}\nReason: {note}')
    command(label.replace('/','-')+f'-fit-{index}',[repo/'rsi/tools/lab.py','run','--task','bike','--workspace',workspace,'--model',model,'--features',features,'--seed',str(seed),'--attempt-limit','2','--policy',out/'RESEARCHER.md','--hypothesis',note])
    candidate=workspace/f'trial-{index:03d}'
    command(label.replace('/','-')+f'-check-{index}',[repo/'rsi/tools/check_result.py',candidate,'--report',candidate/'CHECK.md'])
def require(name):
    if not (out/name).exists():raise SystemExit('Actor note required: '+name)

if a.phase=='prepare':
    if out.exists():raise SystemExit('Preserve workspace')
    out.mkdir();shutil.copyfile(__file__,out/'run-scientist-labs.py')
    for name in ['screen-scientist-idea.py','check-scientist-screen.py']:shutil.copyfile(repo/'how-did-i-generate-it/rsi/scripts'/name,out/name)
    shutil.copyfile(repo/'how-did-i-generate-it/rsi/validation/SCIENTIST-LABS-PROTOCOL.md',out/'PROTOCOL.md')
    save('COMMANDS.csv','action,exit,wall_seconds')
    paths=['rsi/tools/lab.py','rsi/tools/check_result.py','rsi/examples/bike-demand/source/hour.csv',*[f'how-did-i-generate-it/rsi/scripts/{name}' for name in ['run-scientist-labs.py','screen-scientist-idea.py','check-scientist-screen.py']]]
    table('SOURCE-HASHES.csv',['path','sha256'],[(name,sha(repo/name)) for name in paths])
    save('RESEARCHER.md','# Fixed classroom researcher\n\nRead an observed limitation. State a falsifiable question, one changed factor, alternatives, and a rejection condition before fitting. Freeze task and resource rules. Execute only the declared bounded comparison and verify saved predictions. Retain weak results. Use prior evidence to select the next question, with exposure explicit. Review the claim and answer a testable criticism with a predeclared comparison. Separate task results from changes to this research procedure. Do not edit this file during these four labs.\n\nAllocation: 10.18 two fits; 10.19 two screen fits plus two confirmation/ablation fits; 10.20 two follow-up fits; 10.21 zero fits. No final model evaluation.')
    save('RESEARCHER-FREEZE.md','# Frozen researcher\n\nSHA-256: '+sha(out/'RESEARCHER.md'))
    source=repo/'rsi/evidence/2026-09-21/aide-labs/10-13/experiment/trial-002'
    for name in ['RESULT.md','error-by-hour.csv','CHECK.md']:
        destination=out/'starting-evidence'/name;destination.parent.mkdir(exist_ok=True);shutil.copyfile(source/name,destination)
    table('STARTING-SOURCES.csv',['path','sha256'],[(str((source/name).relative_to(repo)).replace('\\','/'),sha(source/name)) for name in ['RESULT.md','error-by-hour.csv','CHECK.md']])
    save('EXPOSURE.md','# Previously exposed development task\n\nThe author has seen earlier bike outcomes and public final-partition aggregates. The copied starting record is historical selection evidence. Current hypotheses precede current fits, not prior knowledge. No final evaluation is requested. The source CSV is publicly readable; loading it to select development rows is not an access-control boundary.')
elif a.phase=='hypothesis':
    absent('10-18/experiment');require('10-18/HYPOTHESIS.md');freeze()
    digest=sha(out/'10-18/HYPOTHESIS.md');save('10-18/HYPOTHESIS-FREEZE.md','# Before fits\n\nSHA-256: '+digest)
    fit('10-18','linear','calendar',17,1,'Baseline for the weather-input hypothesis; fixed linear recipe and calendar inputs.')
    fit('10-18','linear','all',17,2,'Add permitted observed weather fields; same linear recipe and fixed development split.')
    if sha(out/'10-18/HYPOTHESIS.md')!=digest:raise SystemExit('Hypothesis changed')
    print((out/'10-18/experiment/trials.csv').read_text())
elif a.phase=='screen':
    absent('10-19/screen');require('10-19/SCREENING-PLAN.md');freeze()
    digest=sha(out/'10-19/SCREENING-PLAN.md');save('10-19/PLAN-FREEZE.md','# Before screen fits\n\nSHA-256: '+digest)
    results=[]
    for model in ['tree','forest']:
        folder=out/'10-19/screen'/model
        command('screen-'+model,[out/'screen-scientist-idea.py','--repo',repo,'--output',folder,'--model',model])
        command('screen-check-'+model,[out/'check-scientist-screen.py','--source',repo/'rsi/examples/bike-demand/source/hour.csv','--candidate',folder])
        report=fields(folder/'RESULT.md');results.append([model,report['Selection MAE'],report['Fit and prediction seconds']])
    if sha(out/'10-19/SCREENING-PLAN.md')!=digest:raise SystemExit('Screening plan changed')
    table('10-19/SCREEN.csv',['model','selection_mae','fit_seconds'],results)
    print((out/'10-19/SCREEN.csv').read_text())
elif a.phase=='confirm':
    absent('10-19/confirmation/experiment');require('10-19/ADVANCEMENT.md');freeze()
    screen=rows(out/'10-19/SCREEN.csv')
    selected=min(screen,key=lambda r:(float(r['selection_mae']),0 if r['model']=='tree' else 1))['model']
    if fields(out/'10-19/ADVANCEMENT.md')['Selected model']!=selected:raise SystemExit('Advancement violates frozen selection rule')
    digest=sha(out/'10-19/ADVANCEMENT.md');save('10-19/ADVANCEMENT-FREEZE.md','# Before full fits\n\nSHA-256: '+digest)
    fit('10-19/confirmation',selected,'all',17,1,'Confirm the selected nonlinear estimator under full development conditions.')
    fit('10-19/confirmation','linear','all',17,2,'Ablate the estimator replacement by restoring linear; same weather inputs and conditions.')
    if sha(out/'10-19/ADVANCEMENT.md')!=digest:raise SystemExit('Advancement changed')
    print((out/'10-19/confirmation/experiment/trials.csv').read_text())
elif a.phase=='followup':
    absent('10-20/experiment');require('10-20/REVIEW.md');require('10-20/FOLLOWUP-PLAN.md');freeze()
    selected=fields(out/'10-19/ADVANCEMENT.md')['Selected model']
    for name in ['REVIEW.md','FOLLOWUP-PLAN.md']:save('10-20/'+name.replace('.md','-FREEZE.md'),'# Before follow-up\n\nSHA-256: '+sha(out/'10-20'/name))
    fit('10-20',selected,'all',29,1,'Review-driven repeat at seed 29; test the selected estimator without claiming broad seed robustness.')
    fit('10-20','linear','all',29,2,'Matched ablation baseline for the seed-29 follow-up.')
    print((out/'10-20/experiment/trials.csv').read_text())
elif a.phase=='seal':
    absent('MANIFEST.csv');freeze()
    ledgers=[out/'10-18/experiment/trials.csv',out/'10-19/confirmation/experiment/trials.csv',out/'10-20/experiment/trials.csv']
    if [len(rows(x)) for x in ledgers]!=[2,2,2]:raise SystemExit('Unexpected standard fit allocation')
    fits=[r for ledger in ledgers for r in rows(ledger)]
    if any(r['status']!='ok' for r in fits):raise SystemExit('Inspect unsuccessful fit')
    screen=rows(out/'10-19/SCREEN.csv')
    if len(screen)!=2:raise SystemExit('Unexpected screening allocation')
    elapsed=sum(float(r['seconds']) for r in fits)+sum(float(r['fit_seconds']) for r in screen)
    commands=rows(out/'COMMANDS.csv')
    save('COST.md',f'# Counted costs\n\nFits: 8\nSeparate prediction checks: 8\nRecorded fit-related seconds: {elapsed:.9f}\nSubprocess calls: {len(commands)}\nSubprocess wall seconds: {sum(float(r["wall_seconds"]) for r in commands):.9f}\n\nThe six standard fit timings include their tool overhead; two screen timings cover fit and prediction. Timing scopes differ slightly and are not precise hardware benchmarks. All are included in subprocess wall time; do not add these totals. Author reasoning and provider inference costs are unknown. No final evaluation or additional lineage-audit fit occurred.')
    for lab in ['10-18','10-19','10-20','10-21']:save(lab+'/LAB-NOTE.md','# Author walkthrough\n\nLearner prediction, teach-back, and quiz: not attempted. All review roles share the author context. Read the actual files and claim audit for evidence and limits.')
    save('PROGRESS.md','# Stopped at eight fits\n\nAll declared fits and checks complete. No remaining fit budget and no live subprocess. Preserve the original hypotheses, weak screens, review, follow-up, and unchanged researcher identity. Next: publication and separate learner/agent/backend checks.')
    table('MANIFEST.csv',['path','bytes','sha256'],[(p.relative_to(out).as_posix(),p.stat().st_size,sha(p)) for p in sorted(out.rglob('*')) if p.is_file()])
    print((out/'COST.md').read_text())
