"""The system prompt and the catalog, generated by Node and cached as files.

`node prompt.mjs` prints catalog.prompt(); `node catalog_json.mjs` prints the
components as JSON Schema. Both run once, when the cache file is missing, so
the server starts without Node after the first run. Delete the cache files to
regenerate them after editing catalog.mjs.
"""

import shutil
import subprocess
from pathlib import Path

STEP = Path(__file__).resolve().parent
PROMPT_FILE = STEP / "prompt.txt"
CATALOG_FILE = STEP / "catalog.json"


def _cached(cache_file, script):
    if not cache_file.exists():
        node = shutil.which("node")
        if node is None:
            raise RuntimeError(f"{cache_file.name} is missing and node is not on PATH")
        result = subprocess.run([node, script], cwd=STEP, capture_output=True, text=True, encoding="utf-8", check=True)
        cache_file.write_text(result.stdout, encoding="utf-8")
    return cache_file.read_text(encoding="utf-8")


def system_prompt():
    """The text of catalog.prompt(), from prompt.txt."""
    return _cached(PROMPT_FILE, "prompt.mjs")


def catalog_json():
    """The components with their JSON Schema props, from catalog.json."""
    import json

    return json.loads(_cached(CATALOG_FILE, "catalog_json.mjs"))
